### ISSUE TITLE
Graphs loading stuck at 30%

### ISSUE THREAD

**Issue by vertangelx** [0x1d00ffff/0xBTC-Stats#2]
Loading graphs are stuck at 30%  (https://0x1d00ffff.github.io/0xBTC-Stats/?page=graphs&#)

    Loading info from the blockchain... 30%

Tons of errors in the js console

    using gtag
    ?page=graphs&:78 0.12s  0xBitcoin Stats v0.0.13
    ?page=graphs&:78 0.14s  GRAPHS selected
    ?page=graphs&:78 0.15s  updating progress.. ( 0 %)
    ?page=graphs&:78 0.17s  DOMready
    ?page=graphs&:78 0.20s  loaded latest_eth_block: 5857368
    ?page=graphs&:78 0.21s  updating progress.. ( 15 %)
    ?page=graphs&:78 0.25s  updating progress.. ( 30 %)
    ?page=graphs&:78 0.28s  error reading block storage: Error: [ethjs-rpc] rpc error with payload {"id":49023663257,"jsonrpc":"2.0","params":["0xB6eD7644C69416d67B522e20bC294A9a9B405B31","0x6","0x593354"],"method":"eth_getStorageAt"} null
        at ethjs.js:8452
        at XMLHttpRequest.request.onreadystatechange (ethjs.js:8273)
    ?page=graphs&:78 0.31s  error reading block storage: Error: [ethjs-rpc] rpc error with payload {"id":49023663263,"jsonrpc":"2.0","params":["0xB6eD7644C69416d67B522e20bC294A9a9B405B31","0x6","0x58ac55"],"method":"eth_getStorageAt"} null
        at ethjs.js:8452
        at XMLHttpRequest.request.onreadystatechange (ethjs.js:8273)
    ?page=graphs&:78 0.32s  error reading block storage: Error: [ethjs-rpc] rpc error with payload {"id":49023663262,"jsonrpc":"2.0","params":["0xB6eD7644C69416d67B522e20bC294A9a9B405B31","0x6","0x58c2d4"],"method":"eth_getStorageAt"} null
        at ethjs.js:8452
        at XMLHttpRequest.request.onreadystatechange (ethjs.js:8273)
    ?page=graphs&:78 0.36s  error reading block storage: Error: [ethjs-rpc] rpc error with payload {"id":49023663264,"jsonrpc":"2.0","params":["0xB6eD7644C69416d67B522e20bC294A9a9B405B31","0x6","0x5895d5"],"method":"eth_getStorageAt"} null
        at ethjs.js:8452
        at XMLHttpRequest.request.onreadystatechange (ethjs.js:8273)

...

Using Chrome on Windows.

**Comment by 0x1d00ffff** [comment]
Thanks for the report, turns out this was caused by Infura returning 'null' while under a lot of load. 

I added some code to automatically retry when this happens. During testing it seemed that only one or two retries were necessary to load everything - so if Infura gets loaded heavily again it should slow the page load a little instead of preventing it completely.
